export const BUS_STOP_ARRIVALS = 'BUS_STOP_ARRIVALS';
export type BUS_STOP_ARRIVALS = typeof BUS_STOP_ARRIVALS;

export const GET_BUS_STOPS_REQUEST = 'GET_BUS_STOPS_REQUEST';
export type GET_BUS_STOPS_REQUEST = typeof GET_BUS_STOPS_REQUEST;

export const GET_BUS_STOPS_RESPONSE = 'GET_BUS_STOPS_RESPONSE';
export type GET_BUS_STOPS_RESPONSE = typeof GET_BUS_STOPS_RESPONSE;